### PR TITLE
Make error message about GITHUB_TOKEN more concise

### PR DESCRIPTION
**Pull request by leotsarev**

### CODE REVIEW

**Comment by shalzz** [comment]
Are your really hitting this error message? 
`GITHUB_TOKEN` is automatically set by the action runtime for every job and the `TOKEN` var allows overriding it with a PAT.
Its very unlikely anyone will hit this error case in any scenario

**Comment by leotsarev** [comment]
Strangely, I have.
Here is my yml https://github.com/leotsarev/leotsarev.ru/blob/master/.github/workflows/main.yml

**Comment by shalzz** [comment]
Oh, It seems it could be in cases where TOKEN is specified in the workflow yaml but the secret.TOKEN is not set within your repo's settings.

**Comment by shalzz** [comment]
Merged, Thanks!

**Pull request merged**
