### PR TITLE
Support custom build directory

### PR DESCRIPTION
**Pull request by Folyd**
This PR can enable the user to build a custom directory by using env `BUILD_DIR`:
```yml
on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        BUILD_DIR: docs
        TOKEN: ${{ secrets.TOKEN }}
```

### CODE REVIEW

**Comment by shalzz** [comment]
Hi @Folyd 

Thanks for opening a PR. 
Looks great but seems like you are trying to specify a custom build dir option rather than a deploy directory,  something like `BUILD_DIR` might be a better name for the env variable.
Can you also update the README to add the example and explain it under the `Environment Variables` section

**Comment by Folyd** [comment]
Hi @shalzz . Thanks for the review. I submitted a new commit to fix that. Please check it. Thanks. :)

**Comment by shalzz** [comment]
@Folyd It might be a little late for me to be pointing this out, but have you tried solving your use-case with the `working-directory` option described [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun)?
I'm not sure if we can use this with `uses` option instead of `run` but it'd be great if you can check if it is indeed the case.

**Comment by Folyd** [comment]
@shalzz Thanks for the pointing. Unfortunately, afraid this wouldn't work with the `uses` option.

**Comment by shalzz** [comment]
@Folyd thought so, thanks for confirming.

**Comment by Folyd** [comment]
Awesome! I use this workflow to deploy [rust-search-extension](https://github.com/Folyd/rust-search-extension) website, just work like a charm!

**Comment by shalzz** [comment]
Great, glad you like it.
Nice project, will definitely check it out later.

**Pull request merged**
