### PR TITLE
Document permissions setting for GITHUB_TOKEN

### PR DESCRIPTION
**Pull request by azriel91**
Without this, the push will fail, but it is difficult to discover where to configure it.

### CODE REVIEW

**Comment by shalzz** [comment]
Hi, `GITHUB_TOKEN` is available by default on every repo with correct permissions. Are you sure this has changed?

**Comment by azriel91** [comment]
Hm, I'm not sure if the default has changed, but the repo I created ([first commit 2023-01-24](https://github.com/azriel91/peace_website/commit/b5085509bafd3486942cef673d6d8c431cbd1e48)) had it on the **Read repository contents and packages permissions** option.

Someone else encountered this (https://github.com/ad-m/github-push-action/issues/96#issuecomment-889984928), though it *seems* random -- maybe it depends on the last repository one has forked / created.

**Comment by azriel91** [comment]
Heya, looks like Github changed the default: [Updating the default GITHUB_TOKEN permissions to read-only](https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/):

> Previously, GitHub Actions gets a GITHUB_TOKEN with both read/write permissions by default whenever Actions is enabled on a repository.
> As a default, this is too permissive, so to improve security we would like to change the default going forward to a read-only token. You can still flip it to read/write if needed.

**Comment by shalzz** [comment]
Ok, I see. Thanks, merged!

**Pull request merged**
