### PR TITLE
Upgrade_to_zola_19

### PR DESCRIPTION
**Pull request by c-git**
Wasn't sure what else was needed but gave it a go based on the commit I saw in the history

### CODE REVIEW

**Comment by Mikopet** [comment]
This would be nice!

Also using perhaps `0.19.1` already?
@shalzz opinion?

**Comment by c-git** [comment]
Yeah if there is a newer version we should go to that. When I did the PR I did it to the latest version. But not sure if @shalzz  has time to approve. So not sure updating the PR is worth it.

**Comment by Mikopet** [comment]
tbh it would be better to separate the action version number from zola version number, so everybody could just update it from ENV

**Comment by shalzz** [comment]
Superseded by 9c5ce0cfc2be6e802d28bd6d977f00f0e366bd7c

> tbh it would be better to separate the action version number from zola version number, so everybody could just update it from ENV
It's not possible to build a docker image with GH actions env variables.

**Comment by Mikopet** [comment]
> It's not possible to build a docker image with GH actions env variables.

That's true, and because of that the overridden version (if not matching with the default baked-in version) could be acquired in the ENTRYPOINT, what _can_ use ENVs and args.

**Pull request closed without merging**
