### PR TITLE
fix  #13 fatal: could not read Password

### LINKED ISSUE #13: fatal: could not read Password for 'https://***@github.com': No such device or address
I was having this error when setting up my website (https://github.com/naps62/naps62.github.io)

In my previous setup, with gatsby, I had this:

```sh
git remote set-url origin https://naps62:${{ secrets.GITHUB_TOKEN }}@github.com/naps62/naps62.github.io
```

notice that I'm using `naps62:TOKEN` instead of just `TOKEN`
As a hotfix to make this action work, I added `naps62:` as a prefix to the secret string.

Is this something I'm missing, like a permission on the token itself? or is it a bug with how this action uses the token?

### PR DESCRIPTION
**Pull request by Tsai002**
#13 

thanks https://github.com/shalzz/zola-deploy-action/issues/13#issuecomment-777211609

### CODE REVIEW

**Comment by shalzz** [comment]
Does this work without a [Personal Access Key](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) ?

**Comment by Tsai002** [comment]
@shalzz yes! zero configuration.

https://github.com/Tsai002/tsai002.github.io/blob/master/.github/workflows/main.yml

I didn't create any token to make that work.

**Comment by shalzz** [comment]
In that case it might be better to update `entrypoint.sh` with it.

Can you test this [branch](https://github.com/shalzz/zola-deploy-action/tree/no-pat) to see if it works including the changes being published to the {username}.github.io page?
You can select a branch in your action by changing 
`      uses: shalzz/zola-deploy-action@master
`
to this line:
`      uses: shalzz/zola-deploy-action@no-pat
`

**Comment by Tsai002** [comment]
@shalzz  it works.

https://github.com/Tsai002/tsai002.github.io/runs/4831902226?check_suite_focus=true

**Comment by shalzz** [comment]
Okay, Thanks a lot. Merged as 2b54c2ce4f2dbee926eb270e77831323fe1b2a0d

**Pull request closed without merging**
